GET http://localhost:8080/register

###

POST http://localhost:8080/register 
Content-Type: application/json

{
    "username": "New user",
    "email": "user@gmail.com",
    "password": "12345678",
    "confirmPassword": "12345678"
}

###

GET http://localhost:8080/login

### 

POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "12345678"
}

###

GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXJuYW1lIiwiaWF0IjoxNjE4NzU3MTIxLCJleHAiOjE2MTg3NTc3MjF9.6jVtuFRyrr5CGPlD6HaWBBlbh9zZcxE9oZP0QfeYFzQ

###

GET http://localhost:8080/posts/607c459ec38e2804f40d4fcf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXJuYW1lIiwiaWF0IjoxNjE4NzU3MTIxLCJleHAiOjE2MTg3NTc3MjF9.6jVtuFRyrr5CGPlD6HaWBBlbh9zZcxE9oZP0QfeYFzQ

###

POST http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXJuYW1lIiwiaWF0IjoxNjE4NzU1ODM0LCJleHAiOjE2MTg3NTY0MzR9.HiPlzjcbOsqbnrGNNH-eg4FJ_O19Yf9JeCIt_MiYZeM
Content-Type: application/json

{
    "title": "Post title",
    "content": "Post content"
}

### 

POST http://localhost:8080/login/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmV3IHVzZXIiLCJpYXQiOjE2MTg2NzU1ODV9.6_NeGWnrtRCxDFN2FH92w2e_Vw4BXHVySy2RVJJV4As"
}

###

DELETE http://localhost:8080/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmV3IHVzZXIiLCJpYXQiOjE2MTg2NzU1ODV9.6_NeGWnrtRCxDFN2FH92w2e_Vw4BXHVySy2RVJJV4As"
}

###

GET http://localhost:8080/users

###

POST http://localhost:8080/users/edit
Content-Type: application/json

{
    "id": "607b105520f8c42be03c49fe",
    "username": "Username"
}

###

GET http://localhost:8080/api/image/1618752325839-95d2b5818a5a2618a566f926e0293594.jpg

###